#!/usr/bin/env node
// One generator, N outputs. Reads each machine's machine.json (the single source of truth for
// STRUCTURE) and emits the per-language structure (enums/unions + edges) plus proves each committed
// structure.json is derivable from the spec. Behavior (guards/reducers) is hand-written per language and
// bound to the generated edges by NAME. Zero dependencies (Node fs/path/url only).
//
//   node tools/state-machine-codegen/generate.mjs           # write the generated files
//   node tools/state-machine-codegen/generate.mjs --check   # exit 1 if any committed file is stale

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const CHECK = process.argv.includes('--check');

// One entry per machine. csOut is wired when the C# demo machines land (Trax.Samples); tsOut and the
// structure golden are the source of truth this repo owns.
const MACHINES = [
  {
    name: 'turnstile',
    spec: 'machines/turnstile/machine.json',
    structure: 'machines/turnstile/structure.json',
    tsOut: 'src/machines/turnstile/turnstile.g.ts',
  },
  {
    name: 'checkout',
    spec: 'machines/checkout/machine.json',
    structure: 'machines/checkout/structure.json',
    tsOut: 'src/machines/checkout/checkout.g.ts',
  },
];

let drift = false;

function read(rel) {
  return fs.readFileSync(path.join(REPO_ROOT, rel), 'utf8');
}

function writeOrCheck(rel, content) {
  const abs = path.join(REPO_ROOT, rel);
  if (CHECK) {
    const current = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : '';
    if (current !== content) {
      drift = true;
      console.error(`  DRIFT  ${rel} (stale — run the generator)`);
    } else {
      console.log(`  ok     ${rel}`);
    }
    return;
  }
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, content);
  console.log(`  wrote  ${rel}`);
}

// UTF-16 code-unit compare == C# StringComparer.Ordinal == JS default sort.
const ordinal = (a, b) => (a < b ? -1 : a > b ? 1 : 0);

function deriveStructure(spec) {
  return {
    id: spec.id,
    version: spec.version,
    initialState: spec.initialState,
    states: [...spec.states].sort(ordinal),
    triggers: [...spec.triggers].sort(ordinal),
    transitions: spec.transitions
      .map((t) => ({ from: t.from, trigger: t.trigger, to: t.to }))
      .sort((a, b) => ordinal(a.from, b.from) || ordinal(a.trigger, b.trigger) || ordinal(a.to, b.to)),
  };
}

function pascal(name) {
  return name
    .split(/[-_]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

function tsUnion(values) {
  return values.map((v) => `'${v}'`).join(' | ');
}

function tsEdge(edge) {
  const parts = [`from: '${edge.from}'`, `trigger: '${edge.trigger}'`, `to: '${edge.to}'`];
  if (edge.guard) parts.push(`guard: '${edge.guard}'`);
  if (edge.guardMessage) parts.push(`guardMessage: ${JSON.stringify(edge.guardMessage)}`);
  if (edge.reduce) parts.push(`reduce: '${edge.reduce}'`);
  return `  { ${parts.join(', ')} },`;
}

function emitTypescript(spec) {
  const P = pascal(spec.name);
  const lines = [];
  lines.push(`// AUTO-GENERATED by tools/state-machine-codegen/generate.mjs from machines/${spec.name}/machine.json.`);
  lines.push('// Do not edit by hand. Behavior (guards/reducers) is hand-written and bound to these edges by name.');
  lines.push('');
  lines.push(`export type ${P}State = ${tsUnion(spec.states)};`);
  lines.push(`export type ${P}Trigger = ${tsUnion(spec.triggers)};`);
  lines.push('');
  lines.push(`export interface ${P}Edge {`);
  lines.push(`  from: ${P}State;`);
  lines.push(`  trigger: ${P}Trigger;`);
  lines.push(`  to: ${P}State;`);
  lines.push('  guard?: string;');
  lines.push('  guardMessage?: string;');
  lines.push('  reduce?: string;');
  lines.push('}');
  lines.push('');
  lines.push(`export const ${spec.name.replace(/[-_](.)/g, (_, c) => c.toUpperCase())}Structure = {`);
  lines.push(`  id: '${spec.id}',`);
  lines.push(`  version: ${spec.version},`);
  lines.push(`  initialState: '${spec.initialState}' as ${P}State,`);
  lines.push(`  states: [${spec.states.map((s) => `'${s}'`).join(', ')}] as readonly ${P}State[],`);
  lines.push(`  edges: [`);
  for (const edge of spec.transitions) lines.push(`  ${tsEdge(edge)}`);
  lines.push(`  ] as readonly ${P}Edge[],`);
  lines.push('};');
  lines.push('');
  return lines.join('\n');
}

for (const machine of MACHINES) {
  const spec = JSON.parse(read(machine.spec));
  spec.name = machine.name;

  // 1. Emit the TypeScript structure.
  writeOrCheck(machine.tsOut, emitTypescript(spec));

  // 2. Prove the committed structure.json golden is derivable from the spec.
  const golden = JSON.parse(read(machine.structure));
  delete golden._comment;
  const derived = deriveStructure(spec);
  if (JSON.stringify(derived) !== JSON.stringify(golden)) {
    drift = true;
    console.error(`  DRIFT  ${machine.structure} is not derivable from ${machine.spec}`);
  } else {
    console.log(`  ok     ${machine.structure} is derivable`);
  }
}

if (CHECK && drift) {
  console.error('\nGenerated files are stale. Run: node tools/state-machine-codegen/generate.mjs');
  process.exit(1);
}
