-- Gives a state-machine draft an owner kind, and the columns a machine that invokes trains needs
-- (Trax.Effect.StateMachine.Persistence). Columns mirror SnapshotDraft exactly.
--
-- owner_kind: 'user' or 'system'. A user row names its user in user_key; a system row, created only
-- from code by IMachineInstances.Start, has no user key at all. A reserved key string could not mark
-- system rows, because each host maps principals to keys in its own ISnapshotPrincipal and any host's
-- mapping could produce it. Every existing row is a user's, so the column defaults to 'user'.
--
-- invoke_token: the external id of the train run the current state invoked, set when an invoking state
-- is entered and cleared when it is left. An outcome is applied with UPDATE ... WHERE invoke_token =
-- the run's, so it is unique where set. It is server-only and never part of the snapshot.
--
-- The key: user_key becomes nullable, and a key column cannot be, so the primary key moves to a
-- surrogate row_id. Identity is two partial unique indexes: (user_key, machine, id) among user rows,
-- which is the key 051 gave every row, and (machine, id) among system rows. The user index is built
-- before the old key is dropped, so a host still running the previous version never writes a duplicate
-- in between. That host keeps working: it inserts without owner_kind or row_id (both default), and its
-- reads name a user_key, which a system row never matches.
--
-- (machine, state) indexes the operator listing of instances by state.
--
-- Every statement checks before it changes anything, so the script can run again over its own result.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'snapshot_owner_kind' AND n.nspname = 'trax'
    ) THEN
        CREATE TYPE trax.snapshot_owner_kind AS ENUM ('user', 'system');
    END IF;
END $$;

ALTER TABLE trax.snapshot_draft
    ADD COLUMN IF NOT EXISTS owner_kind trax.snapshot_owner_kind NOT NULL DEFAULT 'user';

ALTER TABLE trax.snapshot_draft
    ADD COLUMN IF NOT EXISTS invoke_token text NULL;

ALTER TABLE trax.snapshot_draft
    ADD COLUMN IF NOT EXISTS row_id bigint GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX IF NOT EXISTS ux_snapshot_draft_user_machine_id
    ON trax.snapshot_draft (user_key, machine, id)
    WHERE owner_kind = 'user';

CREATE UNIQUE INDEX IF NOT EXISTS ux_snapshot_draft_system_machine_id
    ON trax.snapshot_draft (machine, id)
    WHERE owner_kind = 'system';

CREATE UNIQUE INDEX IF NOT EXISTS ux_snapshot_draft_invoke_token
    ON trax.snapshot_draft (invoke_token)
    WHERE invoke_token IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_snapshot_draft_machine_state
    ON trax.snapshot_draft (machine, state);

-- The old key is found by kind rather than by name, as 051 does, because a table an older host built
-- with EF's EnsureCreated carries EF's name for it.
DO $$
DECLARE
    old_key text;
    old_columns text[];
BEGIN
    SELECT c.conname,
           array_agg(a.attname::text ORDER BY k.ord)
    INTO old_key, old_columns
    FROM pg_constraint c
    CROSS JOIN LATERAL unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
    JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
    WHERE c.conrelid = 'trax.snapshot_draft'::regclass AND c.contype = 'p'
    GROUP BY c.conname;

    IF old_columns = ARRAY['row_id'] THEN
        RETURN;
    END IF;

    IF old_key IS NOT NULL THEN
        EXECUTE format('ALTER TABLE trax.snapshot_draft DROP CONSTRAINT %I', old_key);
    END IF;

    ALTER TABLE trax.snapshot_draft
        ADD CONSTRAINT pk_snapshot_draft PRIMARY KEY (row_id);
END $$;

ALTER TABLE trax.snapshot_draft
    ALTER COLUMN user_key DROP NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'trax.snapshot_draft'::regclass
          AND conname = 'ck_snapshot_draft_owner'
    ) THEN
        ALTER TABLE trax.snapshot_draft
            ADD CONSTRAINT ck_snapshot_draft_owner CHECK (
                (owner_kind = 'user' AND user_key IS NOT NULL)
                OR (owner_kind = 'system' AND user_key IS NULL)
            );
    END IF;
END $$;
