-- The state a train declared with Checkpoint<TState>(), stored when its run reached that step, so a
-- later run of the same input resumes there instead of running every step before it again
-- (Trax.Docs/adr/0047). The model is Trax.Effect.Models.Checkpoint, on IDataContext.Checkpoints.
-- Trax never stores a run's Memory: a row holds the declared state and the tracks taken before it.
--
-- id: the row's identity.
-- metadata_id: the run that reached the checkpoint. A checkpoint belongs to its run and goes with
--   it: the cascade keeps every existing delete of metadata (cleanup, manifest pruning) working
--   without knowing this table exists. uq_checkpoint_run_node leads with it, so that index serves
--   the cascade and every lookup of a run's rows, and no second index is needed.
-- node_id: the declared node's id as Trax.Core numbers it, Checkpoint<CheckedFindings>#0, or
--   Parallel#0/embedding/Checkpoint<EmbeddingScores>#0 inside a branch, whose path is already in
--   the id. One row per run and node.
-- branch_path: the Parallel branch the checkpoint was taken in (Parallel#0/embedding), null outside
--   any branch. A resume into a failed Parallel reruns each branch from its own latest checkpoint.
-- state_type: the state's type, readable, for display and error messages only. Nothing matches on it.
-- state: the declared state as canonical JSON, under the cap a requeue's stored input uses. Never a
--   placeholder: a state over the cap fails the step and stores nothing. Run data, which no operator
--   surface returns.
-- tracks: the tracks the routing steps before the checkpoint took, in order, as a JSON array. A
--   resume takes them rather than routing again. Empty when nothing routed.
-- chain_hash: ChainGraph.Hash of the declared graph when the row was written, 64 lowercase hex
--   characters. A resume refuses a row whose hash differs from the running chain's.
-- state_fingerprint: the state type's serializer contract when the row was written. A resume
--   refuses a row whose fingerprint differs, since its JSON would read back as a different value.
-- created_at: when the checkpoint was written.
--
-- Every statement checks before it changes anything, so the script can run again over its own result.
CREATE TABLE IF NOT EXISTS trax.checkpoint (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metadata_id bigint NOT NULL REFERENCES trax.metadata (id) ON DELETE CASCADE,
    node_id text NOT NULL,
    branch_path text,
    state_type text NOT NULL,
    state jsonb NOT NULL,
    tracks jsonb NOT NULL DEFAULT '[]',
    chain_hash text NOT NULL,
    state_fingerprint text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_checkpoint_run_node UNIQUE (metadata_id, node_id)
);

-- Which run a run resumes, and where. Set on the queued entry by a manifest's retry, a dead
-- letter's requeue or an operator's resume, and carried to the run's metadata at dispatch, as
-- replay_decisions_of is. resume_at is the node id to resume at, or null for after the latest
-- checkpoint of the run named by resume_from. Not a foreign key, mirroring replay_decisions_of:
-- the cleanup keeps a run while something still resumes it, and a resumed run follows its
-- checkpoints back through the metadata link.
ALTER TABLE trax.work_queue ADD COLUMN IF NOT EXISTS resume_from bigint;

ALTER TABLE trax.work_queue ADD COLUMN IF NOT EXISTS resume_at text;

ALTER TABLE trax.metadata ADD COLUMN IF NOT EXISTS resume_from bigint;

ALTER TABLE trax.metadata ADD COLUMN IF NOT EXISTS resume_at text;

-- A run is resumed by at most one queued entry at a time: an operator's resume racing a manifest's
-- retry queues one and the other is refused. The application checks first; this index holds where
-- two checks race. The column is new, so no entry holds a duplicate to clear first. Built
-- CONCURRENTLY so enqueue and dispatch keep writing while it builds (effect/0014).
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS ix_work_queue_unique_queued_resume
    ON trax.work_queue (resume_from)
    WHERE status = 'queued' AND resume_from IS NOT NULL;

-- The metadata cleanup keeps a run while a run that stays resumes it, and a resume follows a run's
-- checkpoints back through this link. Few runs carry one, so the index is partial; built
-- CONCURRENTLY so the build does not block writes to metadata (effect/0014).
CREATE INDEX CONCURRENTLY IF NOT EXISTS ix_metadata_resume_from
    ON trax.metadata (resume_from) WHERE resume_from IS NOT NULL;
