<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Trax.Samples.GraphQLClient</RootNamespace>
    <IsPackable>false</IsPackable>
    <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HotChocolate.AspNetCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <ProjectReference Include="../../../../Trax.Api/src/Trax.Api.GraphQL.Client/Trax.Api.GraphQL.Client.csproj" />
    <ProjectReference Include="../../../../Trax.Api/src/Trax.Api.GraphQL.Client.Trax/Trax.Api.GraphQL.Client.Trax.csproj" />
    <ProjectReference Include="../../../../Trax.Api/src/Trax.Api.GraphQL.Client.Typed/Trax.Api.GraphQL.Client.Typed.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="**/*.graphql" />
  </ItemGroup>
</Project>
