// AUTO-GENERATED by tools/state-machine-codegen/generate.mjs from machines/turnstile/machine.json.
// Do not edit by hand. Behavior (guards/reducers) is hand-written and bound to these edges by name.

export type TurnstileState = 'Locked' | 'Unlocked';
export type TurnstileTrigger = 'Coin' | 'Push';

export interface TurnstileEdge {
  from: TurnstileState;
  trigger: TurnstileTrigger;
  to: TurnstileState;
  guard?: string;
  guardMessage?: string;
  reduce?: string;
}

export const turnstileStructure = {
  id: 'turnstile',
  version: 1,
  initialState: 'Locked' as TurnstileState,
  states: ['Locked', 'Unlocked'] as readonly TurnstileState[],
  edges: [
    { from: 'Locked', trigger: 'Coin', to: 'Unlocked', guard: 'acceptedCoin', guardMessage: "Only a quarter or a dollar is accepted.", reduce: 'recordCoin' },
    { from: 'Unlocked', trigger: 'Push', to: 'Locked', reduce: 'clear' },
  ] as readonly TurnstileEdge[],
};
