// AUTO-GENERATED by tools/state-machine-codegen/generate.mjs from machines/checkout/machine.json.
// Do not edit by hand. Behavior (guards/reducers) is hand-written and bound to these edges by name.

export type CheckoutState = 'Cart' | 'Review' | 'Paid';
export type CheckoutTrigger = 'Next' | 'Back' | 'Pay' | 'Restart';

export interface CheckoutEdge {
  from: CheckoutState;
  trigger: CheckoutTrigger;
  to: CheckoutState;
  guard?: string;
  guardMessage?: string;
  reduce?: string;
}

export const checkoutStructure = {
  id: 'checkout',
  version: 1,
  initialState: 'Cart' as CheckoutState,
  states: ['Cart', 'Review', 'Paid'] as readonly CheckoutState[],
  edges: [
    { from: 'Cart', trigger: 'Next', to: 'Review', guard: 'hasItems', guardMessage: "Add an item before reviewing." },
    { from: 'Review', trigger: 'Back', to: 'Cart' },
    { from: 'Review', trigger: 'Pay', to: 'Paid', guard: 'payable', guardMessage: "A payable order needs items, a positive total, and a receipt.", reduce: 'applyReceipt' },
    { from: 'Paid', trigger: 'Restart', to: 'Cart', reduce: 'freshCart' },
  ] as readonly CheckoutEdge[],
};
