// Introspects the running devhost and writes the SDL to src/mock/schema-sdl.ts.
// The mock layer builds its auto-mock schema from this string, so it must be
// refreshed whenever the Trax GraphQL schema changes.
//
//   npm run mock:schema            # needs the devhost running on :5310
//   TRAX_API_URL=... TRAX_API_KEY=... node scripts/export-schema.mjs
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildClientSchema, getIntrospectionQuery, printSchema } from "graphql";

const URL = process.env.TRAX_API_URL ?? "http://localhost:5310/trax/graphql";
const KEY = process.env.TRAX_API_KEY ?? "admin-key-do-not-use-in-production";
const here = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(here, "../src/mock/schema-sdl.ts");

const res = await fetch(URL, {
  method: "POST",
  headers: { "Content-Type": "application/json", "X-Api-Key": KEY },
  body: JSON.stringify({ query: getIntrospectionQuery() }),
});

if (!res.ok) {
  console.error(`Introspection request failed: HTTP ${res.status}`);
  process.exit(1);
}

const json = await res.json();
if (json.errors) {
  console.error("Introspection returned errors:", JSON.stringify(json.errors, null, 2));
  process.exit(1);
}

// HotChocolate 16 adds its own types under the reserved "__" prefix (__SearchResult,
// __SchemaDefinition). graphql-js refuses to validate a schema containing them, so the mock
// could never execute against it; drop everything "__" that is not standard introspection.
const STANDARD = new Set(["__Schema", "__Type", "__TypeKind", "__Field", "__InputValue", "__EnumValue", "__Directive", "__DirectiveLocation"]);
json.data.__schema.types = json.data.__schema.types.filter(
  (t) => !t.name.startsWith("__") || STANDARD.has(t.name),
);
const sdl = printSchema(buildClientSchema(json.data));
const header =
  "// GENERATED by scripts/export-schema.mjs — do not edit by hand.\n" +
  "// Regenerate with `npm run mock:schema` while the devhost is running.\n";
writeFileSync(OUT, `${header}export const SCHEMA_SDL = ${JSON.stringify(sdl)};\n`);
console.log(`Wrote ${sdl.length} chars of SDL to src/mock/schema-sdl.ts`);
